### PR TITLE
hello: enable pie

### PR DESCRIPTION
**Pull request by globin**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at URL

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at URL

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at URL

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at URL

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at URL

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at URL

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@nixbot build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at /jobset/nixos/pr-4

**Comment by WilliButz** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at /jobset/nixos/pr-4

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at /jobset/nixos/pr-4

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at Use of uninitialized value in concatenation (.) or string at /nix/store/hanf1j2ixmsm5f7xwnwls85gxwy85h13-hydra-2017-09-14/bin/.hydra-create-jobset-wrapped line 89.
/jobset/nixos/pr-4

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at Use of uninitialized value in concatenation (.) or string at /nix/store/hanf1j2ixmsm5f7xwnwls85gxwy85h13-hydra-2017-09-14/bin/.hydra-create-jobset-wrapped line 89.
/jobset/nixos/pr-4

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at http://hydra.mayflower.de:3000/jobset/nixos/pr-4

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at http://hydra.mayflower.de:3000/jobset/nixos/pr-4

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at http://hydra.mayflower.de:3000/jobset/nixos/pr-4

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at http://hydra.mayflower.de:3000/jobset/nixos/pr-4

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at http://hydra.mayflower.de:3000/jobset/nixos/pr-4

**Comment by globin** [comment]
@globin build

**Comment by globin** [comment]
Jobset created at https://hydra.mayflower.de/jobset/nixos/pr-4

**Comment by globin** [comment]
@nixborg build

**Comment by nixborg** [comment]
@globin is not a committer

**Comment by globin** [comment]
@nixborg build

**Comment by nixborg** [comment]
@globin is not a committer

**Comment by globin** [comment]
@nixborg build

**Comment by nixborg** [comment]
Jobset created at https://hydra.mayflower.de/jobset/nixborg-test/pr-4

**Comment by globin** [comment]
@nixborg build

**Comment by nixborg** [comment]
Jobset created at https://hydra.mayflower.de/jobset/nixborg-test/pr-4

**Comment by globin** [comment]
@nixborg build

**Comment by nixborg** [comment]
Jobset created at https://hydra.mayflower.de/jobset/nixborg-test/pr-4

**Comment by globin** [comment]
test

**Comment by globin** [comment]
foo

**Comment by globin** [comment]
fffafs

**Pull request merged**
